// 150 Essential GMAT Vocabulary Words - Organized by Difficulty
const vocabulary = [
    // ===== BEGINNER LEVEL (50 words) =====
    {
        word: "benefit",
        pronunciation: "/ˈbenɪfɪt/",
        definition: "an advantage or profit gained from something",
        example: "The benefit of exercise is improved health.",
        synonyms: "advantage, gain, profit",
        etymology: "From Latin 'benefactum' meaning 'good deed'",
        scenario: "The new policy will benefit all employees.",
        imagePrompt: "A person receiving a positive outcome with upward arrows",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "effective",
        pronunciation: "/ɪˈfektɪv/",
        definition: "successful in producing a desired result",
        example: "The new strategy proved very effective.",
        synonyms: "successful, efficient, productive",
        etymology: "From Latin 'effectivus' meaning 'causing'",
        scenario: "Exercise is effective for weight loss.",
        imagePrompt: "A target with an arrow hitting the bullseye",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "evidence",
        pronunciation: "/ˈevɪdəns/",
        definition: "facts or information indicating truth",
        example: "The evidence supports her claim.",
        synonyms: "proof, facts, data",
        etymology: "From Latin 'evidentia' meaning 'visibility'",
        scenario: "The detective gathered evidence at the crime scene.",
        imagePrompt: "Documents and photographs laid out as proof",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "analyze",
        pronunciation: "/ˈænəˌlaɪz/",
        definition: "examine in detail to understand or explain",
        example: "We need to analyze the market trends carefully.",
        synonyms: "examine, study, investigate",
        etymology: "From Greek 'analyein' meaning 'to break up'",
        scenario: "The financial analyst will analyze quarterly earnings.",
        imagePrompt: "A person examining charts and graphs with a magnifying glass",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "concept",
        pronunciation: "/ˈkɑːnsept/",
        definition: "an abstract idea or general notion",
        example: "The concept of democracy varies across cultures.",
        synonyms: "idea, notion, principle",
        etymology: "From Latin 'conceptus' meaning 'something conceived'",
        scenario: "The marketing team developed a new concept for the campaign.",
        imagePrompt: "A lightbulb with abstract thought bubbles around it",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "consistent",
        pronunciation: "/kənˈsɪstənt/",
        definition: "acting in the same way over time; unchanging",
        example: "Her performance has been consistent all year.",
        synonyms: "steady, uniform, reliable",
        etymology: "From Latin 'consistere' meaning 'to stand firm'",
        scenario: "Consistent effort leads to long-term success.",
        imagePrompt: "A steady heartbeat line on a monitor showing regularity",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "factor",
        pronunciation: "/ˈfæktər/",
        definition: "a circumstance that contributes to a result",
        example: "Weather is an important factor in crop yields.",
        synonyms: "element, component, variable",
        etymology: "From Latin 'factor' meaning 'maker'",
        scenario: "Multiple factors contributed to the project's success.",
        imagePrompt: "Puzzle pieces showing different contributing elements",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "process",
        pronunciation: "/ˈprɑːses/",
        definition: "a series of actions to achieve a result",
        example: "The hiring process takes about three weeks.",
        synonyms: "procedure, method, system",
        etymology: "From Latin 'processus' meaning 'progress'",
        scenario: "The manufacturing process was streamlined for efficiency.",
        imagePrompt: "A flowchart showing steps in a systematic procedure",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "require",
        pronunciation: "/rɪˈkwaɪər/",
        definition: "need for a particular purpose",
        example: "This position requires five years of experience.",
        synonyms: "need, demand, necessitate",
        etymology: "From Latin 'requirere' meaning 'to seek'",
        scenario: "The recipe requires fresh ingredients for best results.",
        imagePrompt: "A checklist showing necessary requirements",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "source",
        pronunciation: "/sɔːrs/",
        definition: "a place, person, or thing from which something originates",
        example: "The internet is a valuable source of information.",
        synonyms: "origin, foundation, basis",
        etymology: "From Latin 'surgere' meaning 'to rise'",
        scenario: "Scientists traced the pollution to its source.",
        imagePrompt: "A spring of water flowing from a mountain",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "structure",
        pronunciation: "/ˈstrʌktʃər/",
        definition: "the arrangement of parts in a complex entity",
        example: "The company's organizational structure is hierarchical.",
        synonyms: "framework, organization, arrangement",
        etymology: "From Latin 'structura' meaning 'a building'",
        scenario: "The bridge's structure can withstand heavy loads.",
        imagePrompt: "A detailed architectural framework or skeleton",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "establish",
        pronunciation: "/ɪˈstæblɪʃ/",
        definition: "set up on a firm or permanent basis",
        example: "The company aims to establish market leadership.",
        synonyms: "create, found, set up",
        etymology: "From Latin 'stabilire' meaning 'to make firm'",
        scenario: "The research establishes a clear connection.",
        imagePrompt: "Foundation stones being laid for a permanent structure",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "significant",
        pronunciation: "/sɪɡˈnɪfɪkənt/",
        definition: "sufficiently great or important to be worthy of attention",
        example: "The results show significant improvement.",
        synonyms: "important, notable, considerable",
        etymology: "From Latin 'significare' meaning 'to indicate'",
        scenario: "The merger will have significant market impact.",
        imagePrompt: "A large mountain peak standing prominently against the sky",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "assess",
        pronunciation: "/əˈses/",
        definition: "evaluate or estimate the nature, ability, or quality",
        example: "We need to assess the project's viability.",
        synonyms: "evaluate, appraise, judge",
        etymology: "From Latin 'assidere' meaning 'to sit beside'",
        scenario: "The expert will assess the property's value.",
        imagePrompt: "A person with a clipboard carefully examining and rating items",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "innovation",
        pronunciation: "/ˌɪnəˈveɪʃən/",
        definition: "a new method, idea, or product",
        example: "The company is known for technological innovation.",
        synonyms: "invention, breakthrough, novelty",
        etymology: "From Latin 'innovare' meaning 'to renew'",
        scenario: "Innovation drives competitive advantage in business.",
        imagePrompt: "A bright lightbulb surrounded by gears and modern technology",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "collaborate",
        pronunciation: "/kəˈlæbəˌreɪt/",
        definition: "work jointly on an activity or project",
        example: "Teams collaborate more effectively with good tools.",
        synonyms: "cooperate, work together, partner",
        etymology: "From Latin 'collaborare' meaning 'to work together'",
        scenario: "Scientists collaborate across borders on research.",
        imagePrompt: "Multiple people working together around a shared workspace",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "approach",
        pronunciation: "/əˈproʊtʃ/",
        definition: "a way of dealing with something",
        example: "We need a new approach to solve this problem.",
        synonyms: "method, strategy, technique",
        etymology: "From Latin 'appropriare' meaning 'to go nearer to'",
        scenario: "The teacher's innovative approach engaged all students.",
        imagePrompt: "Multiple paths leading to the same destination",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "identify",
        pronunciation: "/aɪˈdentɪˌfaɪ/",
        definition: "establish or recognize who or what something is",
        example: "Can you identify the main issues in this report?",
        synonyms: "recognize, determine, pinpoint",
        etymology: "From Latin 'identitas' meaning 'sameness'",
        scenario: "The doctor will identify the cause of the symptoms.",
        imagePrompt: "A person pointing to specific items in a lineup",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "create",
        pronunciation: "/kriˈeɪt/",
        definition: "bring something into existence",
        example: "The artist will create a sculpture for the park.",
        synonyms: "make, produce, generate",
        etymology: "From Latin 'creare' meaning 'to produce'",
        scenario: "The team will create a prototype by next month.",
        imagePrompt: "Hands molding clay into a beautiful vase",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "develop",
        pronunciation: "/dɪˈveləp/",
        definition: "grow or cause to grow gradually",
        example: "The company plans to develop new software.",
        synonyms: "build, expand, advance",
        etymology: "From French 'développer' meaning 'to unwrap'",
        scenario: "Students develop critical thinking through practice.",
        imagePrompt: "A seed growing into a strong tree over time",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "method",
        pronunciation: "/ˈmeθəd/",
        definition: "a particular way of doing something",
        example: "This method of teaching is very effective.",
        synonyms: "technique, approach, system",
        etymology: "From Greek 'methodos' meaning 'pursuit of knowledge'",
        scenario: "The scientific method ensures reliable results.",
        imagePrompt: "A step-by-step instruction manual with clear diagrams",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "period",
        pronunciation: "/ˈpɪriəd/",
        definition: "a length or portion of time",
        example: "This was a difficult period in the company's history.",
        synonyms: "time, era, phase",
        etymology: "From Greek 'periodos' meaning 'circuit'",
        scenario: "The Renaissance was a period of great artistic achievement.",
        imagePrompt: "A timeline showing different historical eras",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "data",
        pronunciation: "/ˈdeɪtə/",
        definition: "facts and statistics collected for analysis",
        example: "The data shows a clear trend toward remote work.",
        synonyms: "information, facts, statistics",
        etymology: "From Latin 'datum' meaning 'something given'",
        scenario: "Big data analytics help companies make better decisions.",
        imagePrompt: "Charts, graphs, and numbers displayed on computer screens",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "research",
        pronunciation: "/rɪˈsɜːrtʃ/",
        definition: "systematic investigation to establish facts",
        example: "The research revealed surprising results.",
        synonyms: "study, investigation, inquiry",
        etymology: "From French 'recherche' meaning 'to search closely'",
        scenario: "Medical research leads to breakthrough treatments.",
        imagePrompt: "A scientist looking through a microscope in a laboratory",
        difficulty: "beginner",
        category: "academic",
        frequency: "high"
    },
    {
        word: "economic",
        pronunciation: "/ˌiːkəˈnɑːmɪk/",
        definition: "relating to economics or the economy",
        example: "The economic impact of the pandemic was severe.",
        synonyms: "financial, monetary, fiscal",
        etymology: "From Greek 'oikonomikos' meaning 'household management'",
        scenario: "Economic policies affect everyone's daily life.",
        imagePrompt: "Graphs showing economic trends and market fluctuations",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "individual",
        pronunciation: "/ˌɪndɪˈvɪdʒuəl/",
        definition: "single; separate; relating to one person",
        example: "Each individual has unique talents and abilities.",
        synonyms: "person, single, separate",
        etymology: "From Latin 'individuus' meaning 'indivisible'",
        scenario: "Individual effort contributes to team success.",
        imagePrompt: "One person standing out from a crowd",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "policy",
        pronunciation: "/ˈpɑːləsi/",
        definition: "a course of action adopted by a government or organization",
        example: "The new policy will improve workplace safety.",
        synonyms: "rule, regulation, guideline",
        etymology: "From Greek 'politeia' meaning 'citizenship'",
        scenario: "Company policies help ensure fair treatment of all employees.",
        imagePrompt: "A document with official rules and regulations",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "available",
        pronunciation: "/əˈveɪləbəl/",
        definition: "able to be used or obtained",
        example: "The manager is available for meetings this afternoon.",
        synonyms: "accessible, obtainable, ready",
        etymology: "From Latin 'valere' meaning 'to be strong'",
        scenario: "Online resources are available 24/7 for students.",
        imagePrompt: "An open door with a welcome sign",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "technology",
        pronunciation: "/tekˈnɑːlədʒi/",
        definition: "application of scientific knowledge for practical purposes",
        example: "Technology has revolutionized communication.",
        synonyms: "innovation, advancement, tools",
        etymology: "From Greek 'tekhnologia' meaning 'systematic treatment'",
        scenario: "Educational technology enhances learning experiences.",
        imagePrompt: "Modern devices and digital interfaces interconnected",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "environment",
        pronunciation: "/ɪnˈvaɪrənmənt/",
        definition: "the surroundings in which someone operates",
        example: "A positive work environment boosts productivity.",
        synonyms: "surroundings, setting, atmosphere",
        etymology: "From French 'environ' meaning 'around'",
        scenario: "The learning environment affects student performance.",
        imagePrompt: "A beautiful natural landscape with clean air and water",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "community",
        pronunciation: "/kəˈmjuːnəti/",
        definition: "a group of people living or working together",
        example: "The community came together to help flood victims.",
        synonyms: "group, society, neighborhood",
        etymology: "From Latin 'communitas' meaning 'fellowship'",
        scenario: "Online communities connect people with shared interests.",
        imagePrompt: "People of different backgrounds working together harmoniously",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "authority",
        pronunciation: "/əˈθɔːrəti/",
        definition: "the power to give orders or make decisions",
        example: "The manager has the authority to approve budgets.",
        synonyms: "power, control, command",
        etymology: "From Latin 'auctoritas' meaning 'invention'",
        scenario: "Local authorities issued new safety regulations.",
        imagePrompt: "A person in a leadership position making important decisions",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "information",
        pronunciation: "/ˌɪnfərˈmeɪʃən/",
        definition: "facts provided or learned about something",
        example: "The brochure contains useful information about the program.",
        synonyms: "data, facts, details",
        etymology: "From Latin 'informare' meaning 'to shape'",
        scenario: "Accurate information is essential for good decision-making.",
        imagePrompt: "Books, documents, and digital screens displaying knowledge",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "response",
        pronunciation: "/rɪˈspɑːns/",
        definition: "a reaction to something",
        example: "Her response to the criticism was very professional.",
        synonyms: "reply, reaction, answer",
        etymology: "From Latin 'respondere' meaning 'to answer'",
        scenario: "The company's response to the crisis was swift and effective.",
        imagePrompt: "An echo bouncing back from a mountain",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "specific",
        pronunciation: "/spəˈsɪfɪk/",
        definition: "clearly defined or identified",
        example: "Please give me specific examples of the problem.",
        synonyms: "particular, exact, precise",
        etymology: "From Latin 'specificus' meaning 'of a particular kind'",
        scenario: "The contract includes specific terms and conditions.",
        imagePrompt: "A magnifying glass focusing on a particular detail",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "system",
        pronunciation: "/ˈsɪstəm/",
        definition: "a set of connected parts forming a complex whole",
        example: "The school's computer system needs an upgrade.",
        synonyms: "network, organization, arrangement",
        etymology: "From Greek 'systema' meaning 'organized whole'",
        scenario: "The solar system contains eight planets.",
        imagePrompt: "Interconnected gears working together smoothly",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "issue",
        pronunciation: "/ˈɪʃuː/",
        definition: "an important topic or problem for debate",
        example: "Climate change is a pressing global issue.",
        synonyms: "problem, matter, concern",
        etymology: "From Latin 'exire' meaning 'to go out'",
        scenario: "The team worked together to resolve the technical issue.",
        imagePrompt: "A question mark hovering over a complex problem",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "theory",
        pronunciation: "/ˈθɪəri/",
        definition: "a system of ideas explaining something",
        example: "Einstein's theory of relativity changed physics.",
        synonyms: "hypothesis, concept, principle",
        etymology: "From Greek 'theoria' meaning 'contemplation'",
        scenario: "The theory was supported by experimental evidence.",
        imagePrompt: "A complex diagram showing scientific relationships",
        difficulty: "beginner",
        category: "academic",
        frequency: "high"
    },
    {
        word: "legal",
        pronunciation: "/ˈliːɡəl/",
        definition: "relating to the law",
        example: "You should seek legal advice before signing the contract.",
        synonyms: "lawful, legitimate, valid",
        etymology: "From Latin 'legalis' meaning 'of the law'",
        scenario: "Legal requirements must be met before construction begins.",
        imagePrompt: "A gavel and law books on a judge's bench",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "section",
        pronunciation: "/ˈsekʃən/",
        definition: "a distinct part of something",
        example: "Please read section three of the manual.",
        synonyms: "part, portion, segment",
        etymology: "From Latin 'sectio' meaning 'a cutting'",
        scenario: "The sports section of the newspaper is very popular.",
        imagePrompt: "A pie chart divided into different colored sections",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "management",
        pronunciation: "/ˈmænɪdʒmənt/",
        definition: "the process of controlling or dealing with things",
        example: "Good time management is essential for success.",
        synonyms: "administration, control, supervision",
        etymology: "From Latin 'manus' meaning 'hand'",
        scenario: "The company's management team made the final decision.",
        imagePrompt: "A person orchestrating multiple tasks and people efficiently",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "function",
        pronunciation: "/ˈfʌŋkʃən/",
        definition: "the purpose or role of something",
        example: "The function of this button is to save your work.",
        synonyms: "purpose, role, job",
        etymology: "From Latin 'functio' meaning 'performance'",
        scenario: "Each organ has a specific function in the body.",
        imagePrompt: "A key fitting perfectly into its designated lock",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "financial",
        pronunciation: "/faɪˈnænʃəl/",
        definition: "relating to money and finance",
        example: "The company released its financial results yesterday.",
        synonyms: "monetary, economic, fiscal",
        etymology: "From French 'financier' meaning 'to pay'",
        scenario: "Financial planning helps secure your future.",
        imagePrompt: "Charts showing money flow and investment growth",
        difficulty: "beginner",
        category: "business",
        frequency: "high"
    },
    {
        word: "major",
        pronunciation: "/ˈmeɪdʒər/",
        definition: "important, serious, or significant",
        example: "This is a major breakthrough in cancer research.",
        synonyms: "important, significant, main",
        etymology: "From Latin 'major' meaning 'greater'",
        scenario: "The major challenge is finding qualified staff.",
        imagePrompt: "A large building towering over smaller structures",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "similar",
        pronunciation: "/ˈsɪmələr/",
        definition: "having characteristics in common",
        example: "The two proposals are very similar in scope.",
        synonyms: "alike, comparable, equivalent",
        etymology: "From Latin 'similis' meaning 'like'",
        scenario: "Similar problems often have similar solutions.",
        imagePrompt: "Two nearly identical objects side by side",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "various",
        pronunciation: "/ˈveriəs/",
        definition: "different from one another; diverse",
        example: "The conference attracted people from various industries.",
        synonyms: "different, diverse, assorted",
        etymology: "From Latin 'varius' meaning 'changing'",
        scenario: "The restaurant offers various vegetarian options.",
        imagePrompt: "A colorful array of different fruits and vegetables",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "cultural",
        pronunciation: "/ˈkʌltʃərəl/",
        definition: "relating to culture and customs",
        example: "The city is known for its rich cultural heritage.",
        synonyms: "social, traditional, ethnic",
        etymology: "From Latin 'cultura' meaning 'cultivation'",
        scenario: "Cultural differences can enrich workplace diversity.",
        imagePrompt: "People in traditional costumes celebrating together",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },
    {
        word: "education",
        pronunciation: "/ˌedʒuˈkeɪʃən/",
        definition: "the process of learning and teaching",
        example: "Education is the key to personal and professional growth.",
        synonyms: "learning, schooling, instruction",
        etymology: "From Latin 'educatio' meaning 'a bringing up'",
        scenario: "Online education has become increasingly popular.",
        imagePrompt: "Students and teacher engaged in active learning",
        difficulty: "beginner",
        category: "academic",
        frequency: "high"
    },
    {
        word: "physical",
        pronunciation: "/ˈfɪzɪkəl/",
        definition: "relating to the body or material things",
        example: "Regular physical exercise improves health.",
        synonyms: "bodily, material, tangible",
        etymology: "From Greek 'physikos' meaning 'natural'",
        scenario: "The physical properties of the material were tested.",
        imagePrompt: "A person exercising and showing physical strength",
        difficulty: "beginner",
        category: "general",
        frequency: "high"
    },

    // ===== INTERMEDIATE LEVEL (50 words) =====
    {
        word: "ubiquitous", 
        pronunciation: "/yuˈbɪkwɪtəs/", 
        definition: "present, appearing, or found everywhere",
        example: "Smartphones have become ubiquitous in modern society.", 
        synonyms: "omnipresent, pervasive, widespread",
        etymology: "From Latin 'ubique' meaning 'everywhere'", 
        scenario: "Coffee shops are ubiquitous in Seattle - there's one on every corner!",
        imagePrompt: "A photorealistic image showing smartphones, WiFi symbols, and digital screens visible everywhere in a modern city street scene",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "ambiguous", 
        pronunciation: "/æmˈbɪɡjuəs/", 
        definition: "open to more than one interpretation; unclear",
        example: "The contract language was ambiguous, leading to disputes.", 
        synonyms: "vague, unclear, equivocal",
        etymology: "From Latin 'ambiguus' meaning 'doubtful'", 
        scenario: "Her ambiguous email left the team unsure about the deadline.",
        imagePrompt: "A person looking confused at a road sign with multiple arrows pointing in different directions",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "scrutinize", 
        pronunciation: "/ˈskruːtəˌnaɪz/", 
        definition: "examine or inspect closely and thoroughly",
        example: "Auditors will scrutinize the financial records.", 
        synonyms: "examine, inspect, analyze",
        etymology: "From Latin 'scrutari' meaning 'to search'", 
        scenario: "The hiring manager will scrutinize every resume carefully.",
        imagePrompt: "A person with a magnifying glass examining documents closely on a desk",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "vindicate", 
        pronunciation: "/ˈvɪndɪˌkeɪt/", 
        definition: "clear someone of blame; show to be right",
        example: "New evidence vindicated the accused.", 
        synonyms: "exonerate, justify, absolve",
        etymology: "From Latin 'vindicare' meaning 'to claim'", 
        scenario: "The DNA test vindicated the wrongly convicted man.",
        imagePrompt: "A person walking free from a courthouse with arms raised in victory",
        difficulty: "intermediate",
        category: "general",
        frequency: "medium"
    },
    {
        word: "plausible", 
        pronunciation: "/ˈplɔːzəbəl/", 
        definition: "seeming reasonable or probable",
        example: "Her explanation seemed plausible to the jury.", 
        synonyms: "believable, credible, feasible",
        etymology: "From Latin 'plausibilis' meaning 'deserving applause'", 
        scenario: "The CEO's turnaround plan sounds plausible to investors.",
        imagePrompt: "A businessperson presenting a convincing chart to an attentive audience",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "aggregate", 
        pronunciation: "/ˈæɡrɪɡət/", 
        definition: "a whole formed by combining parts; total",
        example: "The aggregate score determined the winner.", 
        synonyms: "total, sum, collective",
        etymology: "From Latin 'aggregare' meaning 'to flock together'", 
        scenario: "The aggregate data shows a clear market trend.",
        imagePrompt: "Multiple colorful puzzle pieces coming together to form a complete picture",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "substantiate", 
        pronunciation: "/səbˈstænʃiˌeɪt/", 
        definition: "provide evidence to support or prove",
        example: "Please substantiate your claims with data.", 
        synonyms: "verify, confirm, validate",
        etymology: "From Latin 'substantia' meaning 'substance'", 
        scenario: "The research substantiated the hypothesis with clear results.",
        imagePrompt: "A stack of documents and evidence files supporting a legal case",
        difficulty: "intermediate",
        category: "academic",
        frequency: "high"
    },
    {
        word: "conducive", 
        pronunciation: "/kənˈduːsɪv/", 
        definition: "making a situation or outcome likely or possible",
        example: "A quiet environment is conducive to studying.", 
        synonyms: "favorable, helpful, beneficial",
        etymology: "From Latin 'conducere' meaning 'to lead together'", 
        scenario: "The new policy is conducive to employee productivity.",
        imagePrompt: "A peaceful library study area with perfect lighting and comfortable seating",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "mitigate", 
        pronunciation: "/ˈmɪtɪˌɡeɪt/", 
        definition: "make less severe, serious, or painful",
        example: "The company took steps to mitigate the risks.", 
        synonyms: "reduce, alleviate, diminish",
        etymology: "From Latin 'mitigare' meaning 'to soften'", 
        scenario: "The insurance policy helps mitigate financial losses.",
        imagePrompt: "A protective umbrella shielding people from a storm",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "exemplary", 
        pronunciation: "/ɪɡˈzempləri/", 
        definition: "serving as a desirable model; outstanding",
        example: "Her exemplary work earned her a promotion.", 
        synonyms: "outstanding, exceptional, model",
        etymology: "From Latin 'exemplum' meaning 'example'", 
        scenario: "The student's exemplary behavior impressed all teachers.",
        imagePrompt: "A gold star trophy or medal representing excellence and achievement",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "prevalent", 
        pronunciation: "/ˈprevələnt/", 
        definition: "widespread in a particular area or time",
        example: "Flu is prevalent during winter months.", 
        synonyms: "common, widespread, dominant",
        etymology: "From Latin 'praevalere' meaning 'to be stronger'", 
        scenario: "Remote work has become prevalent in tech companies.",
        imagePrompt: "A map showing widespread dots or coverage across a region",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "contingent", 
        pronunciation: "/kənˈtɪndʒənt/", 
        definition: "subject to chance; dependent on something else",
        example: "The deal is contingent on board approval.", 
        synonyms: "dependent, conditional, subject to",
        etymology: "From Latin 'contingere' meaning 'to touch'", 
        scenario: "Your bonus is contingent on meeting sales targets.",
        imagePrompt: "A chain link showing connection and dependency between elements",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "arbitrary", 
        pronunciation: "/ˈɑːrbɪˌtreri/", 
        definition: "based on random choice rather than reason",
        example: "The decision seemed arbitrary and unfair.", 
        synonyms: "random, capricious, unreasonable",
        etymology: "From Latin 'arbitrarius' meaning 'depending on will'", 
        scenario: "The arbitrary deadline created unnecessary stress.",
        imagePrompt: "A person randomly throwing darts at a board with eyes closed",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "reciprocal", 
        pronunciation: "/rɪˈsɪprəkəl/", 
        definition: "given, felt, or done in return; mutual",
        example: "They have a reciprocal trade agreement.", 
        synonyms: "mutual, shared, corresponding",
        etymology: "From Latin 'reciprocus' meaning 'returning'", 
        scenario: "Trust in relationships should be reciprocal.",
        imagePrompt: "Two people shaking hands in a gesture of mutual agreement",
        difficulty: "intermediate",
        category: "general",
        frequency: "medium"
    },
    {
        word: "inherent", 
        pronunciation: "/ɪnˈhɪrənt/", 
        definition: "existing as a basic or permanent part",
        example: "Risk is inherent in any investment.", 
        synonyms: "intrinsic, built-in, natural",
        etymology: "From Latin 'inhaerere' meaning 'to stick in'", 
        scenario: "Creativity is inherent in all human beings.",
        imagePrompt: "DNA double helix representing something built into the core structure",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "redundant", 
        pronunciation: "/rɪˈdʌndənt/", 
        definition: "not needed; superfluous",
        example: "The software made manual processes redundant.", 
        synonyms: "unnecessary, superfluous, excess",
        etymology: "From Latin 'redundare' meaning 'to overflow'", 
        scenario: "The backup systems aren't redundant - they're essential.",
        imagePrompt: "Multiple identical keys showing unnecessary duplication",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "tangible", 
        pronunciation: "/ˈtændʒəbəl/", 
        definition: "perceptible by touch; clear and definite",
        example: "We need tangible results, not just promises.", 
        synonyms: "concrete, real, substantial",
        etymology: "From Latin 'tangere' meaning 'to touch'", 
        scenario: "The new strategy produced tangible improvements.",
        imagePrompt: "Hands touching a solid, real object like a stone or wooden block",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "discern", 
        pronunciation: "/dɪˈsɜːrn/", 
        definition: "perceive or recognize clearly",
        example: "It's hard to discern truth from fiction online.", 
        synonyms: "distinguish, detect, recognize",
        etymology: "From Latin 'discernere' meaning 'to separate'", 
        scenario: "Good managers can discern talent in their employees.",
        imagePrompt: "A person using binoculars to see clearly into the distance",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "pragmatic", 
        pronunciation: "/præɡˈmætɪk/", 
        definition: "dealing with things practically rather than ideally",
        example: "We need a pragmatic approach to this problem.", 
        synonyms: "practical, realistic, sensible",
        etymology: "From Greek 'pragma' meaning 'deed'", 
        scenario: "Her pragmatic solution saved both time and money.",
        imagePrompt: "A person choosing practical tools over fancy but impractical ones",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "consensus", 
        pronunciation: "/kənˈsensəs/", 
        definition: "general agreement among a group",
        example: "The team reached consensus on the new strategy.", 
        synonyms: "agreement, accord, unity",
        etymology: "From Latin 'consentire' meaning 'to agree'", 
        scenario: "Building consensus takes time but ensures buy-in.",
        imagePrompt: "Multiple hands coming together in the center of a circle",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "comprehensive", 
        pronunciation: "/ˌkɑːmprɪˈhensɪv/", 
        definition: "complete and including everything necessary",
        example: "We need a comprehensive review of policies.", 
        synonyms: "complete, thorough, extensive",
        etymology: "From Latin 'comprehendere' meaning 'to grasp'", 
        scenario: "The comprehensive report covered all aspects.",
        imagePrompt: "A complete puzzle with all pieces perfectly fitted together",
        difficulty: "intermediate",
        category: "academic",
        frequency: "high"
    },
    {
        word: "infrastructure", 
        pronunciation: "/ˈɪnfrəˌstrʌktʃər/", 
        definition: "basic physical systems of a country or organization",
        example: "Good infrastructure supports economic growth.", 
        synonyms: "foundation, framework, structure",
        etymology: "From Latin 'infra' meaning 'below' and 'structure'", 
        scenario: "The city invested heavily in digital infrastructure.",
        imagePrompt: "A network of roads, bridges, and communication towers",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "allocate", 
        pronunciation: "/ˈæləˌkeɪt/", 
        definition: "distribute resources for a particular purpose",
        example: "We need to allocate more budget to marketing.", 
        synonyms: "assign, distribute, designate",
        etymology: "From Latin 'allocare' meaning 'to place'", 
        scenario: "The manager will allocate tasks based on expertise.",
        imagePrompt: "Pie chart showing different portions being distributed",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "optimize", 
        pronunciation: "/ˈɑːptɪˌmaɪz/", 
        definition: "make the best use of a situation or resource",
        example: "We need to optimize our supply chain efficiency.", 
        synonyms: "improve, enhance, perfect",
        etymology: "From Latin 'optimus' meaning 'best'", 
        scenario: "The algorithm optimizes route planning for delivery.",
        imagePrompt: "A smooth, efficient gear system working in perfect harmony",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "facilitate", 
        pronunciation: "/fəˈsɪlɪˌteɪt/", 
        definition: "make an action or process easier",
        example: "Technology can facilitate remote learning.", 
        synonyms: "enable, assist, help",
        etymology: "From Latin 'facilis' meaning 'easy'", 
        scenario: "The new software facilitates project management.",
        imagePrompt: "A bridge connecting two sides, making crossing easier",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "benchmark", 
        pronunciation: "/ˈbentʃmɑːrk/", 
        definition: "a standard point of reference for comparison",
        example: "Industry benchmarks help measure performance.", 
        synonyms: "standard, reference point, criterion",
        etymology: "From surveying marks cut into stone benches", 
        scenario: "The company exceeded all benchmark targets this quarter.",
        imagePrompt: "A measuring ruler or gauge showing standards and comparisons",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "analogy", 
        pronunciation: "/əˈnælədʒi/", 
        definition: "a comparison between things that have similar features",
        example: "He used a sports analogy to explain the strategy.", 
        synonyms: "comparison, similarity, parallel",
        etymology: "From Greek 'analogia' meaning 'proportion'", 
        scenario: "The teacher's analogy helped students understand the concept.",
        imagePrompt: "Two similar objects side by side showing their comparable features",
        difficulty: "intermediate",
        category: "academic",
        frequency: "high"
    },
    {
        word: "hypothesis", 
        pronunciation: "/haɪˈpɑːθəsɪs/", 
        definition: "a proposed explanation that can be tested",
        example: "The scientist tested her hypothesis through experiments.", 
        synonyms: "theory, proposition, assumption",
        etymology: "From Greek 'hypothesis' meaning 'foundation'", 
        scenario: "The hypothesis was supported by the experimental data.",
        imagePrompt: "A scientist looking at test tubes with a question mark above",
        difficulty: "intermediate",
        category: "academic",
        frequency: "high"
    },
    {
        word: "correlation", 
        pronunciation: "/ˌkɔːrəˈleɪʃən/", 
        definition: "a mutual relationship between two or more things",
        example: "There's a strong correlation between exercise and health.", 
        synonyms: "connection, relationship, link",
        etymology: "From Latin 'cor-' meaning 'together' and 'relatio'", 
        scenario: "The data shows correlation but not causation.",
        imagePrompt: "Two graphs showing synchronized patterns or trends",
        difficulty: "intermediate",
        category: "academic",
        frequency: "high"
    },
    {
        word: "feasible", 
        pronunciation: "/ˈfiːzəbəl/", 
        definition: "possible to do easily or conveniently",
        example: "The project timeline seems feasible given our resources.", 
        synonyms: "possible, achievable, viable",
        etymology: "From French 'faisable' meaning 'doable'", 
        scenario: "The engineer confirmed the design is technically feasible.",
        imagePrompt: "A green checkmark on a planning document showing approval",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "preliminary", 
        pronunciation: "/prɪˈlɪməˌneri/", 
        definition: "denoting an action preceding something more important",
        example: "These are just preliminary results.", 
        synonyms: "initial, preparatory, introductory",
        etymology: "From Latin 'prae' meaning 'before' and 'limen' meaning 'threshold'", 
        scenario: "The preliminary report shows promising trends.",
        imagePrompt: "The first step of a staircase leading to higher levels",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "subsequent", 
        pronunciation: "/ˈsʌbsɪkwənt/", 
        definition: "coming after something in time; following",
        example: "Subsequent events proved her right.", 
        synonyms: "following, later, ensuing",
        etymology: "From Latin 'subsequi' meaning 'to follow closely'", 
        scenario: "Subsequent analysis revealed additional insights.",
        imagePrompt: "A timeline showing events following one after another",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "fundamental", 
        pronunciation: "/ˌfʌndəˈmentəl/", 
        definition: "forming a necessary base or core; essential",
        example: "Understanding basics is fundamental to success.", 
        synonyms: "basic, essential, core",
        etymology: "From Latin 'fundamentum' meaning 'foundation'", 
        scenario: "These fundamental principles guide all decisions.",
        imagePrompt: "A strong foundation stone supporting a building structure",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "criterion", 
        pronunciation: "/kraɪˈtɪriən/", 
        definition: "a principle or standard by which something is judged",
        example: "Experience is the main criterion for this position.", 
        synonyms: "standard, measure, benchmark",
        etymology: "From Greek 'kriterion' meaning 'means of judging'", 
        scenario: "The selection criteria are clearly defined.",
        imagePrompt: "A checklist with various standards and requirements marked",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "constitute", 
        pronunciation: "/ˈkɑːnstɪˌtuːt/", 
        definition: "be a part of a whole; form or compose",
        example: "These factors constitute the main challenges.", 
        synonyms: "form, make up, comprise",
        etymology: "From Latin 'constituere' meaning 'to set up'", 
        scenario: "These elements constitute a complete solution.",
        imagePrompt: "Building blocks coming together to form a larger structure",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "derive", 
        pronunciation: "/dɪˈraɪv/", 
        definition: "obtain something from a specified source",
        example: "The company derives most revenue from services.", 
        synonyms: "obtain, get, extract",
        etymology: "From Latin 'derivare' meaning 'to draw off'", 
        scenario: "Scientists derive energy from renewable sources.",
        imagePrompt: "Water flowing from a mountain spring to a river below",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "implies", 
        pronunciation: "/ɪmˈplaɪz/", 
        definition: "strongly suggest the truth of something not explicitly stated",
        example: "His silence implies agreement with the proposal.", 
        synonyms: "suggests, indicates, hints",
        etymology: "From Latin 'implicare' meaning 'to involve'", 
        scenario: "The data implies a need for policy changes.",
        imagePrompt: "A shadow on the wall suggesting the shape of something unseen",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "fluctuate",
        pronunciation: "/ˈflʌktʃuˌeɪt/",
        definition: "rise and fall irregularly in number or amount",
        example: "Gas prices tend to fluctuate with market conditions.",
        synonyms: "vary, oscillate, waver",
        etymology: "From Latin 'fluctuare' meaning 'to wave'",
        scenario: "Stock prices fluctuate based on investor sentiment.",
        imagePrompt: "A graph showing irregular ups and downs over time",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "enhance",
        pronunciation: "/ɪnˈhæns/",
        definition: "improve the quality, value, or extent of something",
        example: "The new features will enhance user experience.",
        synonyms: "improve, augment, boost",
        etymology: "From French 'enhancer' meaning 'to raise'",
        scenario: "Regular exercise can enhance cognitive function.",
        imagePrompt: "A diamond being polished to increase its brilliance",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "incorporate",
        pronunciation: "/ɪnˈkɔːrpəˌreɪt/",
        definition: "include something as part of a whole",
        example: "The design incorporates elements from both cultures.",
        synonyms: "include, integrate, combine",
        etymology: "From Latin 'incorporare' meaning 'to form into a body'",
        scenario: "The new policy incorporates employee feedback.",
        imagePrompt: "Different puzzle pieces being fitted into a larger picture",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "inevitable",
        pronunciation: "/ɪnˈevɪtəbəl/",
        definition: "certain to happen; unavoidable",
        example: "Change is inevitable in today's fast-paced world.",
        synonyms: "unavoidable, certain, inescapable",
        etymology: "From Latin 'inevitabilis' meaning 'that cannot be avoided'",
        scenario: "With automation, some job changes are inevitable.",
        imagePrompt: "A river flowing inevitably toward the ocean",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "neutral",
        pronunciation: "/ˈnuːtrəl/",
        definition: "not supporting either side in a conflict or debate",
        example: "The mediator remained neutral throughout the discussion.",
        synonyms: "impartial, unbiased, objective",
        etymology: "From Latin 'neutralis' meaning 'of neuter gender'",
        scenario: "Switzerland maintained a neutral stance during the war.",
        imagePrompt: "A balanced scale with equal weights on both sides",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "ultimate",
        pronunciation: "/ˈʌltəmət/",
        definition: "being the best or most extreme example of its kind",
        example: "The ultimate goal is to create a sustainable future.",
        synonyms: "final, supreme, maximum",
        etymology: "From Latin 'ultimus' meaning 'last'",
        scenario: "This is the ultimate test of the team's abilities.",
        imagePrompt: "A mountain peak representing the ultimate achievement",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "capacity",
        pronunciation: "/kəˈpæsəti/",
        definition: "the maximum ability to contain or produce",
        example: "The stadium has a seating capacity of 50,000.",
        synonyms: "ability, capability, volume",
        etymology: "From Latin 'capacitas' meaning 'ability to hold'",
        scenario: "The company is operating at full capacity.",
        imagePrompt: "A container showing its maximum filling level",
        difficulty: "intermediate",
        category: "business",
        frequency: "high"
    },
    {
        word: "generate",
        pronunciation: "/ˈdʒenəˌreɪt/",
        definition: "produce or create something",
        example: "Solar panels generate electricity from sunlight.",
        synonyms: "produce, create, make",
        etymology: "From Latin 'generare' meaning 'to beget'",
        scenario: "The new campaign will generate interest in our products.",
        imagePrompt: "A generator producing electricity with sparks and energy",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "maintain",
        pronunciation: "/meɪnˈteɪn/",
        definition: "keep in good condition; continue to have",
        example: "It's important to maintain a healthy work-life balance.",
        synonyms: "preserve, sustain, uphold",
        etymology: "From Latin 'manu tenere' meaning 'to hold in the hand'",
        scenario: "Regular maintenance keeps the equipment running smoothly.",
        imagePrompt: "A person carefully tending to a garden to keep it healthy",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "perspective",
        pronunciation: "/pərˈspektɪv/",
        definition: "a particular attitude or way of regarding something",
        example: "From my perspective, the project was a success.",
        synonyms: "viewpoint, outlook, angle",
        etymology: "From Latin 'perspicere' meaning 'to look through'",
        scenario: "Getting different perspectives improves decision-making.",
        imagePrompt: "Multiple people looking at the same object from different angles",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },
    {
        word: "relevant",
        pronunciation: "/ˈreləvənt/",
        definition: "closely connected or appropriate to what is being discussed",
        example: "Please only share information that is relevant to the topic.",
        synonyms: "pertinent, applicable, related",
        etymology: "From Latin 'relevare' meaning 'to lift up'",
        scenario: "The candidate's experience is highly relevant to this position.",
        imagePrompt: "A key that fits perfectly into its matching lock",
        difficulty: "intermediate",
        category: "general",
        frequency: "high"
    },

    // ===== ADVANCED LEVEL (50 words) =====
    {
        word: "commensurate", 
        pronunciation: "/kəˈmenʃərət/", 
        definition: "corresponding in size or degree; proportionate",
        example: "The salary is commensurate with experience.", 
        synonyms: "proportional, equivalent, matching",
        etymology: "From Latin 'com-' and 'mensura' meaning 'measured together'", 
        scenario: "The punishment should be commensurate with the crime.",
        imagePrompt: "A balanced scale showing equal weights on both sides",
        difficulty: "advanced",
        category: "business",
        frequency: "medium"
    },
    {
        word: "fortuitous", 
        pronunciation: "/fɔːrˈtuːɪtəs/", 
        definition: "happening by chance, especially in a lucky way",
        example: "Their meeting was entirely fortuitous.", 
        synonyms: "accidental, chance, serendipitous",
        etymology: "From Latin 'fortuitus' meaning 'happening by chance'", 
        scenario: "The fortuitous discovery led to a breakthrough.",
        imagePrompt: "Two paths crossing unexpectedly in a beautiful garden setting",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "delineate", 
        pronunciation: "/dɪˈlɪniˌeɪt/", 
        definition: "describe or portray precisely",
        example: "Please delineate your responsibilities clearly.", 
        synonyms: "outline, define, describe",
        etymology: "From Latin 'delineare' meaning 'to sketch out'", 
        scenario: "The contract delineates each party's obligations.",
        imagePrompt: "A detailed architectural blueprint or map with clear boundaries",
        difficulty: "advanced",
        category: "academic",
        frequency: "medium"
    },
    {
        word: "juxtapose", 
        pronunciation: "/ˈdʒʌkstəˌpoʊz/", 
        definition: "place side by side for comparison",
        example: "The report juxtaposes old and new methods.", 
        synonyms: "compare, contrast, place together",
        etymology: "From Latin 'juxta' meaning 'near' and 'ponere' meaning 'to place'", 
        scenario: "The artist juxtaposed modern and classical elements.",
        imagePrompt: "Two contrasting images placed side by side for comparison",
        difficulty: "advanced",
        category: "academic",
        frequency: "low"
    },
    {
        word: "paradigm", 
        pronunciation: "/ˈpærəˌdaɪm/", 
        definition: "a typical example or pattern of something",
        example: "The internet created a new business paradigm.", 
        synonyms: "model, framework, pattern",
        etymology: "From Greek 'paradeigma' meaning 'pattern'", 
        scenario: "Remote work represents a paradigm shift in employment.",
        imagePrompt: "A geometric pattern or framework showing a structured model",
        difficulty: "advanced",
        category: "academic",
        frequency: "medium"
    },
    {
        word: "synthesize", 
        pronunciation: "/ˈsɪnθəˌsaɪz/", 
        definition: "combine elements to form a connected whole",
        example: "The report synthesizes data from multiple sources.", 
        synonyms: "combine, integrate, merge",
        etymology: "From Greek 'synthesis' meaning 'putting together'", 
        scenario: "Researchers synthesize findings into actionable insights.",
        imagePrompt: "Different colored streams flowing together into one river",
        difficulty: "advanced",
        category: "academic",
        frequency: "medium"
    },
    {
        word: "methodology", 
        pronunciation: "/ˌmeθəˈdɑːlədʒi/", 
        definition: "a system of methods used in a particular activity",
        example: "Our research methodology ensures accurate results.", 
        synonyms: "approach, system, procedure",
        etymology: "From Greek 'methodos' meaning 'way of inquiry'", 
        scenario: "The consulting firm's methodology is proven and reliable.",
        imagePrompt: "A flowchart showing systematic steps and processes",
        difficulty: "advanced",
        category: "academic",
        frequency: "medium"
    },
    {
        word: "empirical", 
        pronunciation: "/ɪmˈpɪrɪkəl/", 
        definition: "based on observation or experience rather than theory",
        example: "The conclusion is based on empirical evidence.", 
        synonyms: "observational, experimental, factual",
        etymology: "From Greek 'empeirikos' meaning 'experienced'", 
        scenario: "Empirical research provides the strongest support.",
        imagePrompt: "A researcher observing and recording real-world phenomena",
        difficulty: "advanced",
        category: "academic",
        frequency: "medium"
    },
    {
        word: "erudite",
        pronunciation: "/ˈerəˌdaɪt/",
        definition: "having or showing great knowledge from study",
        example: "The professor's erudite lecture impressed the audience.",
        synonyms: "scholarly, learned, knowledgeable",
        etymology: "From Latin 'eruditus' meaning 'instructed'",
        scenario: "Her erudite analysis of the literature was comprehensive.",
        imagePrompt: "A scholar surrounded by ancient books and scrolls",
        difficulty: "advanced",
        category: "academic",
        frequency: "low"
    },
    {
        word: "obfuscate",
        pronunciation: "/ˈɑːbfəˌskeɪt/",
        definition: "make unclear or confusing",
        example: "The politician tried to obfuscate the real issues.",
        synonyms: "confuse, obscure, muddle",
        etymology: "From Latin 'obfuscare' meaning 'to darken'",
        scenario: "Complex jargon can obfuscate simple concepts.",
        imagePrompt: "Clear text becoming blurred and illegible",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "perspicacious",
        pronunciation: "/ˌpɜːrspɪˈkeɪʃəs/",
        definition: "having keen insight and good judgment",
        example: "Her perspicacious observation solved the mystery.",
        synonyms: "perceptive, astute, shrewd",
        etymology: "From Latin 'perspicax' meaning 'seeing clearly'",
        scenario: "The perspicacious investor spotted the opportunity early.",
        imagePrompt: "An eagle with sharp eyes spotting prey from afar",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "multifarious",
        pronunciation: "/ˌmʌltɪˈferiəs/",
        definition: "having many different aspects or forms",
        example: "The CEO's multifarious responsibilities kept her busy.",
        synonyms: "diverse, varied, manifold",
        etymology: "From Latin 'multifarius' meaning 'manifold'",
        scenario: "The project's multifarious challenges required diverse skills.",
        imagePrompt: "A kaleidoscope showing multiple colorful patterns",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "ephemeral",
        pronunciation: "/ɪˈfemərəl/",
        definition: "lasting for a very short time",
        example: "Social media fame is often ephemeral.",
        synonyms: "temporary, fleeting, transient",
        etymology: "From Greek 'ephemeros' meaning 'lasting a day'",
        scenario: "The beauty of cherry blossoms is ephemeral but memorable.",
        imagePrompt: "A soap bubble floating and about to burst",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "proclivity",
        pronunciation: "/prəˈklɪvəti/",
        definition: "a natural tendency or inclination",
        example: "She has a proclivity for mathematical thinking.",
        synonyms: "tendency, inclination, propensity",
        etymology: "From Latin 'proclivitas' meaning 'inclination'",
        scenario: "His proclivity for detail made him an excellent editor.",
        imagePrompt: "A compass needle naturally pointing toward magnetic north",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "vacillate",
        pronunciation: "/ˈvæsəˌleɪt/",
        definition: "waver between different opinions or actions",
        example: "The committee continued to vacillate on the decision.",
        synonyms: "waver, fluctuate, hesitate",
        etymology: "From Latin 'vacillare' meaning 'to sway'",
        scenario: "Don't vacillate too long or you'll miss the opportunity.",
        imagePrompt: "A pendulum swinging back and forth indecisively",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "magnanimous",
        pronunciation: "/mæɡˈnænəməs/",
        definition: "generous in forgiving; noble in spirit",
        example: "The champion was magnanimous in victory.",
        synonyms: "generous, noble, charitable",
        etymology: "From Latin 'magnus' meaning 'great' and 'animus' meaning 'mind'",
        scenario: "Her magnanimous gesture helped heal the conflict.",
        imagePrompt: "A person extending a helping hand to a fallen competitor",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "supercilious",
        pronunciation: "/ˌsuːpərˈsɪliəs/",
        definition: "behaving as if one is superior to others",
        example: "His supercilious attitude alienated his colleagues.",
        synonyms: "arrogant, condescending, haughty",
        etymology: "From Latin 'supercilium' meaning 'eyebrow'",
        scenario: "The supercilious waiter made dining unpleasant.",
        imagePrompt: "A person with raised eyebrows looking down at others",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "insidious",
        pronunciation: "/ɪnˈsɪdiəs/",
        definition: "harmful but attractive; treacherous",
        example: "The insidious effects of pollution are often unseen.",
        synonyms: "treacherous, subtle, cunning",
        etymology: "From Latin 'insidiosus' meaning 'cunning'",
        scenario: "Misinformation can have insidious effects on society.",
        imagePrompt: "A beautiful but poisonous flower in a garden",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "ameliorate",
        pronunciation: "/əˈmiːliəˌreɪt/",
        definition: "make better or more tolerable",
        example: "The new policy should ameliorate working conditions.",
        synonyms: "improve, enhance, better",
        etymology: "From Latin 'meliorare' meaning 'to make better'",
        scenario: "Exercise can ameliorate symptoms of depression.",
        imagePrompt: "A withered plant being revived with water and sunlight",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "perfunctory",
        pronunciation: "/pərˈfʌŋktəri/",
        definition: "carried out without real interest or care",
        example: "His perfunctory apology lacked sincerity.",
        synonyms: "halfhearted, cursory, superficial",
        etymology: "From Latin 'perfunctorius' meaning 'careless'",
        scenario: "The perfunctory security check missed the problem.",
        imagePrompt: "A person going through motions without paying attention",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "propensity",
        pronunciation: "/prəˈpensəti/",
        definition: "natural tendency to behave in a particular way",
        example: "She has a propensity for taking calculated risks.",
        synonyms: "tendency, inclination, predisposition",
        etymology: "From Latin 'propensus' meaning 'inclined'",
        scenario: "His propensity for innovation drives the company forward.",
        imagePrompt: "Water naturally flowing downhill following its course",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "disparate",
        pronunciation: "/ˈdɪspərət/",
        definition: "essentially different in kind; unrelated",
        example: "The team combined disparate skills to solve the problem.",
        synonyms: "different, distinct, unrelated",
        etymology: "From Latin 'disparatus' meaning 'separated'",
        scenario: "The merger united disparate business units.",
        imagePrompt: "Completely different puzzle pieces that don't fit together",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "enervate",
        pronunciation: "/ˈenərˌveɪt/",
        definition: "cause to feel drained of energy",
        example: "The hot weather tends to enervate most people.",
        synonyms: "weaken, exhaust, debilitate",
        etymology: "From Latin 'enervare' meaning 'to cut the sinews'",
        scenario: "Long meetings can enervate even the most energetic teams.",
        imagePrompt: "A wilted flower drooping from lack of water",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "prodigious",
        pronunciation: "/prəˈdɪdʒəs/",
        definition: "remarkably or impressively great in extent or size",
        example: "Mozart showed prodigious talent from an early age.",
        synonyms: "enormous, immense, extraordinary",
        etymology: "From Latin 'prodigiosus' meaning 'portentous'",
        scenario: "The athlete's prodigious strength amazed spectators.",
        imagePrompt: "A massive redwood tree towering above the forest",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "precocious",
        pronunciation: "/prɪˈkoʊʃəs/",
        definition: "having developed abilities at an earlier age than usual",
        example: "The precocious child read novels by age five.",
        synonyms: "advanced, mature, gifted",
        etymology: "From Latin 'praecox' meaning 'ripening early'",
        scenario: "Her precocious understanding of math impressed teachers.",
        imagePrompt: "A young child solving complex mathematical equations",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "ostentatious",
        pronunciation: "/ˌɑːstenˈteɪʃəs/",
        definition: "designed to impress or attract notice",
        example: "His ostentatious display of wealth was off-putting.",
        synonyms: "showy, flashy, pretentious",
        etymology: "From Latin 'ostentare' meaning 'to display'",
        scenario: "The ostentatious mansion dominated the modest neighborhood.",
        imagePrompt: "A person covered in flashy jewelry and expensive clothes",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "surreptitious",
        pronunciation: "/ˌsɜːrəpˈtɪʃəs/",
        definition: "kept secret, done stealthily",
        example: "She took surreptitious glances at her watch.",
        synonyms: "secret, stealthy, covert",
        etymology: "From Latin 'surreptitius' meaning 'stolen'",
        scenario: "The journalist's surreptitious recording exposed corruption.",
        imagePrompt: "A person secretly taking photos from behind a corner",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "intractable",
        pronunciation: "/ɪnˈtræktəbəl/",
        definition: "hard to control or deal with",
        example: "The intractable problem required innovative solutions.",
        synonyms: "stubborn, unmanageable, difficult",
        etymology: "From Latin 'intractabilis' meaning 'not manageable'",
        scenario: "The intractable conflict lasted for decades.",
        imagePrompt: "A stubborn mule refusing to move despite pulling",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "taciturn",
        pronunciation: "/ˈtæsəˌtɜːrn/",
        definition: "reserved in speech; saying little",
        example: "The taciturn professor rarely spoke in meetings.",
        synonyms: "quiet, reserved, uncommunicative",
        etymology: "From Latin 'taciturnus' meaning 'silent'",
        scenario: "His taciturn nature made him seem mysterious.",
        imagePrompt: "A person sitting quietly while others talk around them",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "tenuous",
        pronunciation: "/ˈtenjuəs/",
        definition: "very weak or slight; having little substance",
        example: "The connection between the events was tenuous at best.",
        synonyms: "weak, slight, flimsy",
        etymology: "From Latin 'tenuis' meaning 'thin'",
        scenario: "Their tenuous relationship couldn't survive the crisis.",
        imagePrompt: "A thin thread barely holding two objects together",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "voracious",
        pronunciation: "/vəˈreɪʃəs/",
        definition: "having a very eager appetite for something",
        example: "She was a voracious reader who devoured books.",
        synonyms: "insatiable, ravenous, eager",
        etymology: "From Latin 'vorax' meaning 'greedy'",
        scenario: "His voracious appetite for learning impressed mentors.",
        imagePrompt: "A person hungrily consuming stacks of books",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "spurious",
        pronunciation: "/ˈspjʊriəs/",
        definition: "not genuine; false or fake",
        example: "The spurious documents were quickly identified as forgeries.",
        synonyms: "false, fake, counterfeit",
        etymology: "From Latin 'spurius' meaning 'illegitimate'",
        scenario: "Spurious claims undermined the research's credibility.",
        imagePrompt: "A counterfeit dollar bill next to a genuine one",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "quixotic",
        pronunciation: "/kwɪkˈsɑːtɪk/",
        definition: "unrealistic and impractical",
        example: "His quixotic plan to save the world seemed naive.",
        synonyms: "idealistic, impractical, unrealistic",
        etymology: "From Don Quixote, Cervantes' idealistic character",
        scenario: "The quixotic venture failed despite good intentions.",
        imagePrompt: "Don Quixote tilting at windmills on his horse",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "torpid",
        pronunciation: "/ˈtɔːrpɪd/",
        definition: "mentally or physically inactive; sluggish",
        example: "The hot afternoon made everyone feel torpid and lazy.",
        synonyms: "sluggish, lethargic, inactive",
        etymology: "From Latin 'torpidus' meaning 'numb'",
        scenario: "The torpid economy needed stimulus to revive growth.",
        imagePrompt: "A sloth moving extremely slowly on a tree branch",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "pedantic",
        pronunciation: "/pɪˈdæntɪk/",
        definition: "overly concerned with minor details or rules",
        example: "The pedantic editor corrected every minor error.",
        synonyms: "nitpicking, fussy, meticulous",
        etymology: "From Italian 'pedante' meaning 'teacher'",
        scenario: "His pedantic approach slowed down the creative process.",
        imagePrompt: "A person with a magnifying glass examining tiny details",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "recalcitrant",
        pronunciation: "/rɪˈkælsɪtrənt/",
        definition: "stubbornly refusing to obey authority",
        example: "The recalcitrant student refused to follow school rules.",
        synonyms: "defiant, obstinate, rebellious",
        etymology: "From Latin 'recalcitrare' meaning 'to kick back'",
        scenario: "The recalcitrant board member blocked every proposal.",
        imagePrompt: "A person crossing arms and turning away defiantly",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "sanguine",
        pronunciation: "/ˈsæŋɡwɪn/",
        definition: "optimistic or cheerful, especially in difficult situations",
        example: "Despite setbacks, she remained sanguine about success.",
        synonyms: "optimistic, hopeful, positive",
        etymology: "From Latin 'sanguineus' meaning 'bloody'",
        scenario: "His sanguine outlook helped the team through tough times.",
        imagePrompt: "A person smiling confidently while facing storm clouds",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "prescient",
        pronunciation: "/ˈpresiənt/",
        definition: "having knowledge of things before they happen",
        example: "Her prescient warnings about the market crash proved accurate.",
        synonyms: "prophetic, foresighted, predictive",
        etymology: "From Latin 'praescire' meaning 'to know beforehand'",
        scenario: "The prescient investor avoided the risky stocks.",
        imagePrompt: "A crystal ball showing future events clearly",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "vitriolic",
        pronunciation: "/ˌvɪtriˈɑːlɪk/",
        definition: "harsh and bitter criticism",
        example: "The vitriolic review destroyed the restaurant's reputation.",
        synonyms: "caustic, bitter, scathing",
        etymology: "From Latin 'vitriolum' meaning 'sulfuric acid'",
        scenario: "The debate became vitriolic and personal.",
        imagePrompt: "Acid burning through metal with harsh, destructive effect",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "paucity",
        pronunciation: "/ˈpɔːsəti/",
        definition: "scarcity; smallness of quantity",
        example: "The paucity of evidence made conviction difficult.",
        synonyms: "scarcity, shortage, lack",
        etymology: "From Latin 'paucitas' meaning 'fewness'",
        scenario: "There's a paucity of qualified candidates for the position.",
        imagePrompt: "A nearly empty container with just a few items",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "mercurial",
        pronunciation: "/mərˈkjʊriəl/",
        definition: "changing moods quickly and unpredictably",
        example: "His mercurial temperament made him hard to work with.",
        synonyms: "volatile, unpredictable, changeable",
        etymology: "From Mercury, the Roman messenger god",
        scenario: "The mercurial market swung wildly between extremes.",
        imagePrompt: "A thermometer rapidly changing between hot and cold",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "parsimonious",
        pronunciation: "/ˌpɑːrsəˈmoʊniəs/",
        definition: "extremely careful with money; stingy",
        example: "The parsimonious manager refused all expense requests.",
        synonyms: "stingy, miserly, frugal",
        etymology: "From Latin 'parsimonia' meaning 'thrift'",
        scenario: "Her parsimonious habits helped her save for retirement.",
        imagePrompt: "A person clutching coins tightly, unwilling to spend",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "cogent",
        pronunciation: "/ˈkoʊdʒənt/",
        definition: "clear, logical, and convincing",
        example: "She made a cogent argument for increasing the budget.",
        synonyms: "convincing, compelling, persuasive",
        etymology: "From Latin 'cogere' meaning 'to drive together'",
        scenario: "The lawyer's cogent presentation swayed the jury.",
        imagePrompt: "A clear, straight arrow hitting the center of a target",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "vicarious",
        pronunciation: "/vaɪˈkeriəs/",
        definition: "experienced through someone else",
        example: "Parents often feel vicarious pride in their children's achievements.",
        synonyms: "indirect, secondhand, substitute",
        etymology: "From Latin 'vicarius' meaning 'substitute'",
        scenario: "She lived vicariously through her favorite characters in books.",
        imagePrompt: "A person watching others achieve something they desire",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "impeccable",
        pronunciation: "/ɪmˈpekəbəl/",
        definition: "flawless; without fault",
        example: "Her impeccable reputation opened many doors.",
        synonyms: "flawless, perfect, faultless",
        etymology: "From Latin 'impeccabilis' meaning 'not liable to sin'",
        scenario: "The chef's impeccable presentation impressed the critics.",
        imagePrompt: "A perfectly cut diamond sparkling without any flaws",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "germane",
        pronunciation: "/dʒərˈmeɪn/",
        definition: "relevant and appropriate to the subject",
        example: "His comments were not germane to the discussion.",
        synonyms: "relevant, pertinent, applicable",
        etymology: "From Latin 'germanus' meaning 'of the same parents'",
        scenario: "Please keep your questions germane to the topic.",
        imagePrompt: "Puzzle pieces that fit perfectly together",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "efficacious",
        pronunciation: "/ˌefɪˈkeɪʃəs/",
        definition: "successful in producing a desired result",
        example: "The new treatment proved efficacious for most patients.",
        synonyms: "effective, successful, productive",
        etymology: "From Latin 'efficax' meaning 'effective'",
        scenario: "The efficacious strategy increased sales by 40%.",
        imagePrompt: "A key successfully opening a locked door",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "dilatory",
        pronunciation: "/ˈdɪləˌtɔːri/",
        definition: "slow to act; causing delay",
        example: "The committee's dilatory response frustrated stakeholders.",
        synonyms: "slow, delaying, procrastinating",
        etymology: "From Latin 'dilatorius' meaning 'tending to delay'",
        scenario: "His dilatory approach cost the company the contract.",
        imagePrompt: "A snail slowly moving while others wait impatiently",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "fastidious",
        pronunciation: "/fæˈstɪdiəs/",
        definition: "very attentive to accuracy and detail",
        example: "The fastidious editor caught every small error.",
        synonyms: "meticulous, particular, careful",
        etymology: "From Latin 'fastidiosus' meaning 'squeamish'",
        scenario: "Her fastidious attention to detail ensured quality.",
        imagePrompt: "A person carefully arranging items with perfect precision",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "gregarious",
        pronunciation: "/ɡrɪˈɡeriəs/",
        definition: "fond of company; sociable",
        example: "His gregarious nature made him popular at parties.",
        synonyms: "sociable, outgoing, friendly",
        etymology: "From Latin 'gregarius' meaning 'of a flock'",
        scenario: "The gregarious salesperson excelled at networking events.",
        imagePrompt: "A person happily surrounded by friends at a gathering",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "indolent",
        pronunciation: "/ˈɪndələnt/",
        definition: "wanting to avoid activity; lazy",
        example: "The indolent student rarely completed assignments on time.",
        synonyms: "lazy, idle, sluggish",
        etymology: "From Latin 'indolens' meaning 'free from pain'",
        scenario: "His indolent approach to work frustrated his manager.",
        imagePrompt: "A person lounging lazily while work piles up around them",
        difficulty: "advanced",
        category: "general",
        frequency: "medium"
    },
    {
        word: "loquacious",
        pronunciation: "/loʊˈkweɪʃəs/",
        definition: "very talkative",
        example: "The loquacious host kept the conversation flowing.",
        synonyms: "talkative, chatty, garrulous",
        etymology: "From Latin 'loquax' meaning 'talkative'",
        scenario: "Her loquacious nature made her perfect for radio.",
        imagePrompt: "A person with multiple speech bubbles flowing from their mouth",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    },
    {
        word: "punctilious",
        pronunciation: "/pʌŋkˈtɪliəs/",
        definition: "showing great attention to detail and correct behavior",
        example: "The punctilious butler ensured everything was perfect.",
        synonyms: "meticulous, precise, scrupulous",
        etymology: "From Latin 'punctum' meaning 'point'",
        scenario: "Her punctilious preparation guaranteed the event's success.",
        imagePrompt: "A person carefully checking items off a detailed checklist",
        difficulty: "advanced",
        category: "general",
        frequency: "low"
    }
];